/*
 * Copyright (C) 2020 Ian Martinez
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package asciistudio;

import ascomponent.ImageSidebarItem;

/**
 *
 * @author Ian Martinez
 */
public class MainWindow extends javax.swing.JFrame {
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();  
        
        for(var i=0; i<20; i++) {
            var sidebarItem = new ImageSidebarItem();
            sidebarItem.setTitle("Image " + i);
            sidebarPanel.add(sidebarItem);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainSplitter = new javax.swing.JSplitPane();
        sidebarScroll = new javax.swing.JScrollPane();
        sidebarPanel = new javax.swing.JPanel();
        settingsImageSplitter = new javax.swing.JSplitPane();
        currentPaletteContainer = new javax.swing.JPanel();
        currentPalette = new ascomponent.PalettePanel();
        beforeAfterSplitter = new javax.swing.JSplitPane();
        originalImage = new javax.swing.JLabel();
        renderedImage = new javax.swing.JLabel();
        mainToolbar = new javax.swing.JToolBar();
        importButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();
        exportTextButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setName("MainWindowFrame"); // NOI18N
        setSize(new java.awt.Dimension(700, 500));

        mainSplitter.setDividerLocation(130);
        mainSplitter.setDoubleBuffered(true);

        sidebarScroll.setBorder(null);
        sidebarScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        sidebarScroll.setMinimumSize(new java.awt.Dimension(120, 5));

        sidebarPanel.setMinimumSize(new java.awt.Dimension(120, 300));
        sidebarPanel.setLayout(new javax.swing.BoxLayout(sidebarPanel, javax.swing.BoxLayout.Y_AXIS));
        sidebarScroll.setViewportView(sidebarPanel);

        mainSplitter.setLeftComponent(sidebarScroll);

        settingsImageSplitter.setDividerLocation(120);
        settingsImageSplitter.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        currentPaletteContainer.setMinimumSize(new java.awt.Dimension(550, 55));
        currentPaletteContainer.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 180;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        currentPaletteContainer.add(currentPalette, gridBagConstraints);

        settingsImageSplitter.setLeftComponent(currentPaletteContainer);

        beforeAfterSplitter.setDividerLocation(400);
        beforeAfterSplitter.setResizeWeight(0.5);

        originalImage.setText("Original");
        beforeAfterSplitter.setLeftComponent(originalImage);

        renderedImage.setText("Rendered");
        beforeAfterSplitter.setRightComponent(renderedImage);

        settingsImageSplitter.setRightComponent(beforeAfterSplitter);

        mainSplitter.setRightComponent(settingsImageSplitter);

        mainToolbar.setRollover(true);

        importButton.setText("Import");
        importButton.setFocusable(false);
        importButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        importButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolbar.add(importButton);

        exportButton.setText("Export");
        exportButton.setFocusable(false);
        exportButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exportButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolbar.add(exportButton);

        exportTextButton.setText("Export Text");
        exportTextButton.setFocusable(false);
        exportTextButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exportTextButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolbar.add(exportTextButton);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        jMenu1.setText("View");
        menuBar.add(jMenu1);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSplitter, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
            .addComponent(mainToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mainToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainSplitter, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JMenuItem aboutMenuItem;
    protected javax.swing.JSplitPane beforeAfterSplitter;
    protected javax.swing.JMenuItem copyMenuItem;
    protected ascomponent.PalettePanel currentPalette;
    protected javax.swing.JPanel currentPaletteContainer;
    protected javax.swing.JMenuItem cutMenuItem;
    protected javax.swing.JMenuItem deleteMenuItem;
    protected javax.swing.JMenu editMenu;
    protected javax.swing.JMenuItem exitMenuItem;
    protected javax.swing.JButton exportButton;
    protected javax.swing.JButton exportTextButton;
    protected javax.swing.JMenu fileMenu;
    protected javax.swing.JMenu helpMenu;
    protected javax.swing.JButton importButton;
    protected javax.swing.JMenu jMenu1;
    protected javax.swing.JSplitPane mainSplitter;
    protected javax.swing.JToolBar mainToolbar;
    protected javax.swing.JMenuBar menuBar;
    protected javax.swing.JMenuItem openMenuItem;
    protected javax.swing.JLabel originalImage;
    protected javax.swing.JMenuItem pasteMenuItem;
    protected javax.swing.JLabel renderedImage;
    protected javax.swing.JMenuItem saveAsMenuItem;
    protected javax.swing.JMenuItem saveMenuItem;
    protected javax.swing.JSplitPane settingsImageSplitter;
    protected javax.swing.JPanel sidebarPanel;
    protected javax.swing.JScrollPane sidebarScroll;
    // End of variables declaration//GEN-END:variables

}
