/*
 * Copyright (C) 2020 Ian Martinez
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package asciicomponent;

/**
 * A UI for showing progress.
 *
 * @author Ian Martinez
 */
public class ProgressPanel extends javax.swing.JPanel {

    private String stage = "";
    private int percent;

    /**
     * Creates new form ProgressPanel
     */
    public ProgressPanel() {
        initComponents();
    }

    /**
     * @return the current progress value
     */
    public int getProgress() {
        return this.progressBar.getValue();
    }

    /**
     * Set the progress value in a range from min to max.
     * 
     * @param value the progress value
     * @param min the min progress value
     * @param max the max progress value
     */
    public void setProgress(int value, int min, int max) {
        percent = (int) ((value / (double) (max - min)) * 100);
        this.progressBar.setValue(percent);
        updateLabel();
    }

    /**
     * Set the progress value, out of 100.
     * 
     * @param value the value
     */
    public void setProgress(int value) {
        this.setProgress(value, 0, 100);
    }

    /**
     * Update the progress label.
     */
    private void updateLabel() {
        if (stage != null && !stage.equals("")) {
            this.progressLabel.setText(stage + ": " + percent + "%");
        } else {
            this.progressLabel.setText(percent + "%");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        progressLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        setLayout(new java.awt.BorderLayout(6, 6));

        progressLabel.setText("0%");
        add(progressLabel, java.awt.BorderLayout.PAGE_START);
        add(progressBar, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel progressLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the stage
     */
    public String getStage() {
        return stage;
    }

    /**
     * @param stage the stage to set
     */
    public void setStage(String stage) {
        this.stage = stage;
        updateLabel();
    }

}
